### PR TITLE
Make Package and Refactor

### PR DESCRIPTION
**Pull request by Mchristos**
This repository is now easily installable as a package. I also refactored some names to make the import statements make a bit more sense. 

- empowerment function in `__init__.py` for a more sensible import statement
- rename `empowerment` -> `compute_empowerment`
- rename module `info_theory` -> `information_theory`
- update README

### CODE REVIEW

**Review by tessavdheiden — DISMISSED** [review]
Great that you make a package. 
requirements.txt instead of requirements.py? 
also, why not put install_requires
    install_requires =[
        'numpy',
    ]
... instead of requirements.py in the setup.py?

**Comment by Mchristos** [comment]
> Great that you make a package.
> requirements.txt instead of requirements.py?
> also, why not put install_requires
> install_requires =[
> 'numpy',
> ]
> ... instead of requirements.py in the setup.py?

You're right, thanks for spotting. Will add an install_requires field and then remove `requirements.py` (should have been `.txt` you're right)

**Comment by Mchristos** [comment]
Thanks @tessavdheiden, I added the requirements to the `setup.py`

**Comment by Mchristos** [comment]
Sorry @tessavdheiden , need you to re-approve after making those changes

**Pull request merged**
